export const nomineeFieldConfig = [
  {
    name: "nominee_name",
    label: "Nominee Full Name",
    type: "text",
    disabled: false,
  },
  {
    name: "share_percentage",
    label: "Share (%)",
    type: "text",
    disabled: false,
  },
  {
    name: "relation",
    label: "Relation",
    type: "select",
    options: [
      { value: "Father", label: "Father" },
      { value: "Mother", label: "Mother" },
      { value: "Brother", label: "Brother" },
      { value: "Sister", label: "Sister" },
      { value: "Spouse", label: "Spouse" },
      { value: "Son", label: "Son" },
      { value: "Daughter", label: "Daughter" },
      { value: "Other", label: "Other" },
    ],
    disabled: false,
  },
  {
    name: "dob",
    label: "Date of Birth",
    type: "date",
    disabled: false,
  },
  {
    name: "guardian_name",
    label: "Guardian Name",
    type: "text",
    dependsOnMinor: true,
    disabled: false,
  },
  {
    name: "guardian_pan_number",
    label: "Guardian PAN",
    type: "text",
    dependsOnMinor: true,
    disabled: false,
  },
  {
    name: "mobile",
    label: "Nominee Mobile Number",
    type: "text",
    disabled: false,
  },
  {
    name: "email",
    label: "Nominee Email",
    type: "text",
    disabled: false,
  },
  {
    name: "is_address_same",
    label: "Address same as applicant?",
    type: "checkbox",
    disabled: false,
  },
  {
    name: "address_line_1",
    label: "Address Line 1",
    type: "text",
    dependsOn: ["is_address_same"],
    disabled: false,
  },
  {
    name: "address_line_2",
    label: "Address Line 2",
    type: "text",
    dependsOn: ["is_address_same"],
    disabled: false,
  },
  {
    name: "address_line_3",
    label: "Address Line 3",
    type: "text",
    dependsOn: ["is_address_same"],
    disabled: false,
  },
  {
    name: "country",
    label: "Country",
    type: "text",
    disabled: true,
    dependsOn: ["is_address_same"],
  },
  {
    name: "state",
    label: "State",
    type: "select",
    options: [
      "Andhra Pradesh",
      "Arunachal Pradesh",
      "Assam",
      "Bihar",
      "Chhattisgarh",
      "Goa",
      "Gujarat",
      "Haryana",
      "Himachal Pradesh",
      "Jharkhand",
      "Karnataka",
      "Kerala",
      "Madhya Pradesh",
      "Maharashtra",
      "Manipur",
      "Meghalaya",
      "Mizoram",
      "Nagaland",
      "Odisha",
      "Punjab",
      "Rajasthan",
      "Sikkim",
      "Tamil Nadu",
      "Telangana",
      "Tripura",
      "Uttar Pradesh",
      "Uttarakhand",
      "West Bengal",
      "Andaman and Nicobar Islands",
      "Chandigarh",
      "Dadra and Nagar Haveli and Daman and Diu",
      "Delhi",
      "Jammu and Kashmir",
      "Ladakh",
      "Lakshadweep",
      "Puducherry",
    ].map((state) => ({ value: state, label: state })),
    dependsOn: ["is_address_same"],
    disabled: false,
  },
  {
    name: "city",
    label: "City",
    type: "text",
    dependsOn: ["is_address_same"],
    disabled: false,
  },
  {
    name: "pin_code",
    label: "Pin Code",
    type: "text",
    dependsOn: ["is_address_same"],
    disabled: false,
  },
  {
    name: "id_proof_type",
    label: "Nominee's ID Proof",
    type: "select",
    disabled: false,
    options: [
      { value: "Pan Card", label: "Pan Card" },
      { value: "Aadhaar Card", label: "Aadhaar Card" },
      { value: "Driving Licence", label: "Driving Licence" },
      { value: "Passport", label: "Passport" },
    ],
  },
  {
    name: "id_proof_number",
    label: "Nominee's ID Proof Number",
    type: "text",
    disabled: false,
  },
];

export const NOMINEE_NO_CONSENT =
  "I / We ${username}, hereby confirm that I / We do not wish to appoint any nominee(s) in my / our trading / demat account and understand the issues involved in non-appointment of nominee(s) and further are aware that in case of death of all the account holder(s), my / our legal heirs would need to submit all the requisite documents / information for claiming of assets held in my / our trading / demat account, which may also include documents issued by Court or other such competent authority, based on the value of assets held in the trading / demat account.";

export const NOMINEE_YES_CONSENT =
  "I want the details of my nominee to be printed in the statement of holding or statement of account, provided to me by the DP as follows:";
